[package]
name = "directory_synchronizer"
version = "0.1.0"
authors = ["jokrey"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jokrey_utilities = { path = "../jokrey_utilities" }
filetime = "0.2.23"
rand = "0.4.6"
